### ISSUE TITLE
exec variable in open_terminal.py is a reserved word

### ISSUE THREAD

**Issue by rla3rd** [mwahlroos/Nautiterm#2]
nice job, did what i wanted, i had to change the "exec" variable name to "exc" in order for it to work

**Comment by mwahlroos** [comment]
Thanks for the feedback!

I'll make that change. In the interest of understanding what's going on, though, do you remember if you got any kind of an error in the terminal where you ran "nautilus -q" (if that's how you restarted the file manager)?

While "exec" is also the name of a built-in function and may thus not be the best variable name, that hadn't caused problems on my system as the built-in isn't being used directly, so it would be interesting to know in which cases it does or doesn't.

**Comment by rla3rd** [comment]
it gave me a plain vanilla syntax error
